### DISCUSSION TITLE
How to restore a specific pvc if backup all

### DISCUSSION THREAD

**Discussion by stevemayster** [k8up-io/k8up#1011] [Q&A] [answered]
Hello.
I try to understand how we can restore specific PV backup if we backup all PV in a cluster
Can you give me an example?
I would appreciate it

**Comment by Kidswiss** [comment]
Hi @stevemayster 

Did you have a look at our restore guide? https://docs.k8up.io/k8up/2.11/how-tos/restore.html

If so, where do you struggle?

**Comment by stevemayster** [comment]
Hello @Kidswiss.
Yes, i read manual and spend some time to googling.
Still don't understand. In manual we create a bucket for S3 and make a backup of all PV.
Then we restore it using same bucket. But what if we have many PV? How to specify the one we need?
Maybe i miss something? Can you please point me to right direction?

**Comment by Kidswiss** [comment, marked as answer]
Hi @stevemayster 

Each snapshot contains exactly one PVC. You can use the `snapshot` objects to determine which ID matches to which PVC, the `paths` field contains the name of the PVC that has been backed up in this snapshot. Then use that ID to do the restore via k8up cli, restic or a restore object.

```yaml
kubectl get snapshots 162e7a85 -oyaml
apiVersion: k8up.io/v1
kind: Snapshot
metadata:
  name: 162e7a85
  namespace: default
spec:
  date: "2023-03-03T07:34:42Z"
  id: 162e7a85acbc14de93dad31a3699331cb32187ff0d7bd2227b7c4362a1d13a42 # ID for the restore
  paths:
  - /data/subject-pvc # Name of the PVC
  repository: s3:http://minio.minio.svc.cluster.local:9000/backup
```

**Comment by stevemayster** [comment]
@Kidswiss many thanks for your answer!
So if i understand you right, i can just specify id of snapshot in restore.yaml. Is it right?

```
---
apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: restore-test-mfw
  namespace: k8up
spec:
  id: 162e7a85acbc14de93dad31a3699331cb32187ff0d7bd2227b7c4362a1d13a42
  podSecurityContext:
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch
  restoreMethod:
    folder:
      claimName: restore-test-mfw
  backend:
    repoPasswordSecretRef:
      name: "restic-repository-password"
      key: "password"
    s3:
      accessKeyIDSecretRef:
        key: username
        name: s3-secrets
      bucket: k8up
      endpoint: http://minio:9000
      secretAccessKeySecretRef:
        key: password
        name: s3-secrets
```
