### DISCUSSION TITLE
Application-Aware backup without PVC, is it possible ?

### DISCUSSION THREAD

**Discussion by owngr** [k8up-io/k8up#1020] [Q&A]
Hello there,

Helm chart version: 4.8.1

I have a django application that use an external postgresql database outside of the cluster and has no PVC.

My goal is to use django builtin command to backup the database as json and I added the following annotations to the deployment:

```yaml
    k8up.io/backupcommand: /home/app/manage.py dumpdata
    k8up.io/file-extension: .json
```

Besides that I have the following schedule:
```yaml
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup
spec:
  # Only way to setup securityContext on the containers
  podConfigRef:
    name: backup-config
  backend:
    swift:
      # Path into the Swift directory 
      path: /backup
      container: backup
    envFrom:
      - secretRef:
          name: backup
    repoPasswordSecretRef:
      name: backup
      key: RESTIC_PASSWORD
  backup:
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
```

And the following  PodConfig for security reasons:
```yaml
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: backup-config
spec:
  template:
    spec:
      containers:
        - name: backup
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000043
            seccompProfile:
              type: RuntimeDefault
```

**What did I expect**
I thought that even though there was no pvc attached to the deployment a backup would start with the backup command, but when I look at the backup object I see the following:

```
Name:         backup-backup-lp6pm
Labels:       <none>
Annotations:  <none>
API Version:  k8up.io/v1
Kind:         Backup
Metadata:
  Creation Timestamp:  2024-10-28T14:40:00Z
  Generation:          1
  Owner References:
    API Version:     k8up.io/v1
    Kind:            Schedule
    Name:            backup
Spec:
  Backend:
    Env From:
      Secret Ref:
        Name:  backup
    Repo Password Secret Ref:
      Key:   RESTIC_PASSWORD
      Name:  backup
    Swift:
      Container:              backup
      Path:                   /backup
  Failed Jobs History Limit:  2
  Pod Config Ref:
    Name:  backup-config
  Resources:
  Successful Jobs History Limit:  2
Status:
  Conditions:
    Last Transition Time:  2024-10-28T14:40:00Z
    Message:               no container definitions found
    Reason:                NoPreBackupPodsFound
    Status:                True
    Type:                  PreBackupPodReady
Events:                    <none>
```

Does k8up needs at least one PVC in order to run a backup ?
