### DISCUSSION TITLE
Sample configuration of k8sup to store backups in Azure BlobStorage

### DISCUSSION THREAD

**Discussion by pascalhobus** [k8up-io/k8up#837] [Q&A] [answered]
Hi,

Is there a sample configuration that shows how to configure a backup so that Azure BlobStorage is used to store backups?

Grüessli,
Pascal

**Comment by Kidswiss** [comment, marked as answer]
HI @pascalhobus 

We haven't really tested it, and I just saw that the API reference is broken for some backends...

But you should be able to configure it via:

```
backend:
  azure:
    container: mycontainer
    accountNameSecretRef:
      name: something
      key: somethingelse
   accountKeySecretRef:
     name: foo
     key: bar
```

This _should_ make k8up backup to an azure blob storage. But as I said it's untested mostly due to us not using azure... Please open issues if you find problems, so we can have a look at it.
