### DISCUSSION TITLE
Use subfolder in s3 bucket?

### DISCUSSION THREAD

**Discussion by diogosilva30** [k8up-io/k8up#921] [Q&A] [answered]
Is it possible to choose a specific subfolder for backups inside an s3 bucket?

I would like to share the same bucket for backups from different clusters.
Let's say a bucket name `k8s-backups` I would want to have:
- `cluster1`
- `cluster2`
- `clustern`

I know velero supports this with `prefix`, but I'd rather use k8up 😄

**Comment by Kidswiss** [comment, marked as answer]
Hi

We currently don't support prefixes for S3 repositories.

However, Restic and K8up support multiple backup source per repository, so you can point all your backups to the same bucket. You won't get any logical separation between the clusters though. The snapshots will all just show up in the same place.

**Reply by diogosilva30** [reply]
Fair enough. Any plans to support it?

**Comment by vedmaka** [comment]
It seems like this is now supported for Backups, but not for Restore? For example, this Schedule configuration works just fine and creates a repository at `/mysql` subdirectory in the bucket:

```yaml
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-schedule-mysql
spec:
  backend:
    s3:
      ...

      bucket: some-bucket-with-backups/mysql

      ...
```

But the Restore like this one leads to `unable to start k8up: restore job failed: Bucket name contains invalid characters` error in the logs:

```yaml
apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: test-restore-s3-1
spec:
  snapshot: ...
  restoreMethod:

    s3:
      ...
      bucket: some-bucket-with-backups/restore
      ...

  backend:
    s3:
      ...
      bucket: some-bucket-with-backups/mysql
      ...

```
