### DISCUSSION TITLE
How to reference a secret that is handled by Kustomize

### DISCUSSION THREAD

**Discussion by Rick-van-Dam** [k8up-io/k8up#984] [Q&A]
So when you use kustomize the secrets get appended a small hash value so you have to reference them like so:
```
    s3:
      endpoint: http://minio:9000
      bucket: backups
      accessKeyIDSecretRef:
        name: minio-credentials-7mghcc79dd
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials-7mghcc79dd
        key: password
```

Everytime the secret value changes the hash changes which is annoying. Any way to just use minio-credentials without the hash value and make it work? Normally kustomize will replace it with the proper value when you use it like so:
```
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: password
```

However that does not seem to happen with the k8up config, iam assuming here because its non standard kubernetes config for secrets.

**Comment by Rick-van-Dam** [comment]
So I was able to do this with kustomize and instead of defining the values on the backed just define them as env var:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: k8up
  releaseName: k8up
  repo: https://k8up-io.github.io/k8up
  version: 4.7.0
  valuesInline:
    k8up:
      envVars:
      - name: BACKUP_GLOBALREPOPASSWORD
        valueFrom:
          secretKeyRef:
            name: backup-repo
            key: password
```

Not a true answer though as its more of a workaround.
