### ISSUE TITLE
RestoreSpec.podConfigRef doesn't seem to work

### ISSUE THREAD

**Issue by deitmerit** [k8up-io/k8up#1019]
### Description

I would like to use RestoreSpec.podConfigRef (to set podAffinity rules, which I need to be able to restore a backup to a ReadWriteOnce PV). However, they don't seem to work.

This is how I set up my Restore and PodConfig resources:

```yaml
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: restore-podconfig
spec:
  template:
    spec:
      containers: [ ]
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - foo
---
apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: restore
spec:
  podConfigRef:
    name: restore-podconfig
  restoreMethod:
    folder:
      claimName: pvc-foo
  backend:
    s3: [...]
    repoPasswordSecretRef:
      name: backup-encryption
      key: password
```

The generated restore pod has no affinity set at all.

BTW, for backups I do the same, and it works.

### Expected Behavior

I expect the generated restore pods to have the affinity set as specified in the PodConfig resource.

### Version of K8up

v4.8.1

### Version of Kubernetes

v1.31.1

### Distribution of Kubernetes

Talos 1.8

**Comment by deitmerit** [comment]
Hmm, after adding a `podSecurityContext` to the Restore resource, the affinity is applied. The `podSecurityContext` however is ignored (podConfig seems to take precedence, as documented)

**Comment by arska** [comment]
Looked at the code — `job.MutateBatchJob()` in `operator/job/job.go` handles the PodConfig merge via `mergo.Merge` with `mergo.WithOverride`. The affinity from the PodConfig should be merged into the Job's pod spec.

However, I notice your PodConfig has `containers: []` (empty list). This might cause `mergo` to overwrite the existing containers with an empty list before the restore executor re-populates them, which could interfere with the merge order.

Could you try with a non-empty containers list?

```yaml
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: restore-podconfig
spec:
  template:
    spec:
      containers:
        - name: restore
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - foo
```

If that doesn't help, could you share the generated Job YAML (`kubectl get job <restore-job> -o yaml`) so we can see what the merge produced?
