### ISSUE TITLE
Add nodeSelector to check/prune/cleanup pods

### ISSUE THREAD

**Issue by codestation** [k8up-io/k8up#1022]
### Summary

**As** an admin\
**I want** to configure on what nodes are the jobs deployed\
**So that** my nodes gets a stable workload.

### Context

Currently the check/prune/cleanup jobs of a scheduled backup doesn't have a nodeSelector config option, so they are launched on any node. This can affect negatively nodes where those unexpected pods are unwanted.

**Comment by arska** [comment]
This is possible via PodConfig, which merges the full pod spec (including `nodeSelector`) into backup/check/prune jobs.

```yaml
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: node-selector-config
spec:
  template:
    spec:
      containers:
        - name: k8up
      nodeSelector:
        kubernetes.io/os: linux
        node-role: backup
```

Then reference it in your Schedule:
```yaml
spec:
  podConfigRef:
    name: node-selector-config
```

See the [PodConfig documentation](https://docs.k8up.io/k8up/latest/how-tos/schedules.html#_customize_pod_spec). Closing as this is already supported.
