### ISSUE TITLE
k8up helm chart v4.8.3 is not respecting env variables correctly

### ISSUE THREAD

**Issue by untcha** [k8up-io/k8up#1043]
### Description

I want to set the environment variable `BACKUP_SKIP_WITHOUT_ANNOTATION=true` directly in the `values.yaml` of the helm chart.

```yaml
...
k8up:
  # -- envVars allows the specification of additional environment variables.
  # See [values.yaml](values.yaml) how to specify
  # See documentation which variables are supported.
  envVars:
    - name: BACKUP_SKIP_WITHOUT_ANNOTATION
      value: "true"
...
```

Unfortunately after applying the helm chart the value of the environment variable is still set to `false`

Checking the resulting resource manifests by running `helm template ...` shows that the environment variable is double set. Once to `true` and once to `false`

```yaml
...
containers:
        - name: k8up-operator
          image: "ghcr.io/k8up-io/k8up:v2.11.3"
          imagePullPolicy: IfNotPresent
          args: [ operator ]
          env:
            - name: BACKUP_IMAGE
              value: "ghcr.io/k8up-io/k8up:v2.11.3"
            - name: TZ
              value: ${TIMEZONE}
            - name: BACKUP_ENABLE_LEADER_ELECTION
              value: "true"
            - name: BACKUP_SKIP_WITHOUT_ANNOTATION
              value: "false"
            - name: BACKUP_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BACKUP_SKIP_WITHOUT_ANNOTATION
              value: "true"
...
```

### Logs

```shell

```

### Expected Behavior

The environment variable should be set only once and overridden when also set in the helm chart `values.yaml`

### Version of K8up

v2.11

### Version of Kubernetes

v1.31.2

### Distribution of Kubernetes

k3s
