### ISSUE TITLE
Can't set RESTIC_PROGRESS_FPS

### ISSUE THREAD

**Issue by gdemeter-kx** [k8up-io/k8up#1047]
### Description

I was trying to set RESTIC_PROGRESS_FPSRESTIC_PROGRESS_FPS via a PodConfig:

```
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: podconfig
spec:
  template:
    spec:
      containers:
        - name: podconfig
          env:
            - name: RESTIC_PROGRESS_FPS
              value: "0.005"
```

Which works as expected, the backup pod got this env var. However, I still saw the following line in it's logs:

`2025-03-03T12:56:45Z    INFO    k8up.restic.restic.snapshots.command    Defining RESTIC_PROGRESS_FPS  {"frequency": 0.016666666666666666}`

I checked what happens in the code: https://github.com/k8up-io/k8up/blob/0e10a932db96ef91d6fb2b69bbb16439e2fcdb73/restic/cli/command.go#L75

The issue is strings.HasPrefix gets it's inputs in the incorrect order: 

`if strings.HasPrefix("RESTIC_PROGRESS_FPS=", envVar)`

See HasPrefix's docs [here](https://www.codecademy.com/resources/docs/go/strings/hasprefix).

```
Syntax
strings.HasPrefix(str, prefix)
```

### Logs

```shell

```

### Expected Behavior

RESTIC_PROGRESS_FPS  is set to the desired value.

### Version of K8up

4.8.3

### Version of Kubernetes

k3s

### Distribution of Kubernetes

k3s
