### ISSUE TITLE
Missing roles in helm chart

### ISSUE THREAD

**Issue by Rick-van-Dam** [k8up-io/k8up#1061]
### Description

Seems the helm chart is missing some roles of the user the k8up pod uses as I see this in the logs:

```
E0426 20:46:40.594063       1 leaderelection.go:332] error retrieving resource lock base/d2ab61da.syn.tools: leases.coordination.k8s.io "d2ab61da.syn.tools" is forbidden: User "system:serviceaccount:base:k8up" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "base"
```

This also seems to prevent k8up from working

### Logs

```shell

```

### Expected Behavior

No error and k8up works

### Steps To Reproduce

1. Install helm chart (I am using talos kubernetes)
2. Check logs

### Version of K8up

2.12.0

### Version of Kubernetes

1.32

### Distribution of Kubernetes

Talos

**Comment by Rick-van-Dam** [comment]
This seems to fix it:

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8up-fix-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8up-fix-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8up-fix-role
subjects:
  - kind: ServiceAccount
    name: k8up
```

**Comment by arska** [comment]
Looking at this — the `coordination.k8s.io/leases` permission is already present in the operator ClusterRole in the Helm chart, and has been since at least chart version 4.8.4 (which ships with operator v2.12.0).

The ClusterRole includes:
```yaml
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
```

Could you check if `rbac.create` is set to `false` in your Helm values? Or if the chart was upgraded from a much older version where the RBAC might not have been updated?

You can verify with:
```bash
kubectl get clusterrole -l app.kubernetes.io/name=k8up -o yaml | grep -A5 coordination
```

If the coordination rules are missing from your cluster, a `helm upgrade` should fix it.
