### ISSUE TITLE
Stats and Prom URLS not properly merged

### ISSUE THREAD

**Issue by Kidswiss** [k8up-io/k8up#535]
### Description

Defining `statsURL` or `promURL` on a job object doesn't pass it to the actual generated jobs. The respective env vars will stay empty.

If setting those on a global level they get applied as intended.

### Additional Context

Tested with v2.0.0-rc3

### Logs

```shell
Not applicable
```

### Expected Behavior

Any `statsURL` or `promURL` set in a job should get respected.

### Steps To Reproduce

1. Run operator without any global URLs configured.
2. Apply a job:
```
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-test
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  statsURL: http://192.168.5.195:8091
  promURL: http://192.168.5.195:9091
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://192.168.5.195:9000
      bucket: k8up
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password
```
3. Resulting pod has empty env vars for the settings.

### Version of K8up

v2.0.0-rc3

### Version of Kubernetes

1.22

### Distribution of Kubernetes

Rancher
