### ISSUE TITLE
Allow setting subpaths for S3 backend

### ISSUE THREAD

**Issue by cwrau** [k8up-io/k8up#615]
### Summary

**As** user
**I want** to specify subpaths for the S3 backend
**So that** I can have a nice structure in my S3

### Context

I want the backups to be grouped by namespace, helmRelease and type, resulting in the following;

HelmRelase `customer-prod` in namespace `customer` backs up PVC `config`. I want the backups to land in the following location;

`s3://k8s-backup/customer/customer-prod/persistentvolumeclaim/config/`

### Acceptance Criteria

- Given a `Backup` resource's `backend.s3`, I want to be able to specify something like a `prefix`

### Implementation Ideas

An (optional) `prefix` field on the S3Spec

**Comment by s4ndalHat** [comment]
Hello, also need this feature, is this on going ? 
Thanks

**Comment by Kidswiss** [comment]
Hi everyone

You can use subpaths S3 like this:
```
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: test
spec:
  backend:
    repoPasswordSecretRef:
      key: password
      name: k8up-repository-password
    s3:
      accessKeyIDSecretRef:
        key: AWS_ACCESS_KEY_ID
        name: backup-bucket-credentials
      bucket: mybucket/path/to/subfolder
      endpoint: http://minio-server.minio.svc:9000
      secretAccessKeySecretRef:
        key: AWS_SECRET_ACCESS_KEY
        name: backup-bucket-credentials
```

The `bucket` field is simply concatenated to build the `RESTIC_REPOSITORY` string as documented here: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3.

So you can simply add the subfolders via slashes.
