### ISSUE TITLE
Tags are not assigned to snaspshots

### ISSUE THREAD

**Issue by alwinmark** [k8up-io/k8up#619]
### Description

It seems like Tags are not working currently for Backup and Schedule Resources.

K8up Helm Version: 2.0.2

### Logs

```shell
restic -r s3://s3.eu-central-1.amazonaws.com/$bucket


repository b5944e6c opened successfully, password is correct
ID        Time                 Host         Tags        Paths
---------------------------------------------------------------------------
cdf9bb5b  2022-03-10 15:29:16  default              /data/foo

```

### Expected Behavior

```
repository b5944e6c opened successfully, password is correct
ID        Time                 Host         Tags        Paths
---------------------------------------------------------------------------
cdf9bb5b  2022-03-10 15:29:16  default     foobar     /data/foo
---------------------------------------------------------------------------
```

### Steps To Reproduce

```
cat <<EOF | kubectl apply -f -
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-test
spec:
  keepJobs: 4
  tags:
  - foobar
  backend:
    repoPasswordSecretRef:
      name: backup-s3-secret
      key: RESTIC_PASSWORD
    s3:
      endpoint: s3.eu-central-1.amazonaws.com
      bucket: backup-k8s-staging
      accessKeyIDSecretRef:
        name: backup-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: backup-s3-secret
        key: AWS_SECRET_ACCESS_KEY
EOF
```

### Version of K8up

ghcr.io/k8up-io/k8up:v2.1.0

### Version of Kubernetes

v1.18.20

### Distribution of Kubernetes

Rancher
