### ISSUE TITLE
K8up operator crashes in panic because of missing API implementation

### ISSUE THREAD

**Issue by ThomasSteinbach** [k8up-io/k8up#638]
### Description

As for Backups I tried to set the `podSecurityContext` within the `backup` definition of a `Schedule`:
https://k8up.io/k8up/2.1/references/api-reference.html#k8s-api-github-com-k8up-io-k8up-api-v1-runnablespec

As described in the API documentation this should be valid, as the `Schedule` specification takes the same `backup` specification as the `Backup` itself.

However setting the `podSecurityContext` leads to a `panic` crash of the K8up operator pod (see Logs section).

### Logs

```shell
logs from the k8up operator pod:


 panic: reflect: call of reflect.Value.Type on zero Value                                                                                                            │
                                                                                                                                                                     │
 goroutine 470 [running]:                                                                                                                                            │
 reflect.Value.Type({0x0, 0x0, 0x16e1060})                                                                                                                           │
     /opt/hostedtoolcache/go/1.17.7/x64/src/reflect/value.go:2262 +0x12e                                                                                             │
 github.com/imdario/mergo.merge({0x16e1060, 0xc0004b4690}, {0x16e1060, 0x0}, {0x0, 0x0, 0x1782a6c})                                                                  │
     /home/runner/go/pkg/mod/github.com/imdario/mergo@v0.3.12/merge.go:363 +0x1c9                                                                                    │
 github.com/imdario/mergo.Merge(...)                                                                                                                                 │
     /home/runner/go/pkg/mod/github.com/imdario/mergo@v0.3.12/merge.go:296                                                                                           │
 github.com/k8up-io/k8up/operator/handler.(*ScheduleHandler).mergeSecurityContextWithDefaults(0xc0009879d8, 0xc00077ac00)                                            │
     /home/runner/work/k8up/k8up/operator/handler/schedule.go:139 +0xce                                                                                              │
 github.com/k8up-io/k8up/operator/handler.(*ScheduleHandler).mergeWithDefaults(0xc00077ab00, 0xc00077ab00)                                                           │
     /home/runner/work/k8up/k8up/operator/handler/schedule.go:108 +0x45                                                                                              │
 github.com/k8up-io/k8up/operator/handler.(*ScheduleHandler).createJobList(0xc0009879d8)                                                                             │
     /home/runner/work/k8up/k8up/operator/handler/schedule.go:93 +0x465                                                                                              │
 github.com/k8up-io/k8up/operator/handler.(*ScheduleHandler).Handle(0xc0009879d8)                                                                                    │
     /home/runner/work/k8up/k8up/operator/handler/schedule.go:47 +0x47                                                                                               │
 github.com/k8up-io/k8up/controllers.(*ScheduleReconciler).Reconcile(0xc0004ff080, {0x19b1970, 0xc0009b64e0}, {{{0xc0007fb110, 0x6}, {0xc000822780, 0x1d}}})         │
     /home/runner/work/k8up/k8up/controllers/schedule_controller.go:60 +0x5a5                                                                                        │
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00049e420, {0x19b1970, 0xc0009b6450}, {{{0xc0007fb110, 0x16b4ea0}, {0xc000822780, │
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f                                                 │
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00049e420, {0x19b18c8, 0xc0003992c0}, {0x15fcbe0, 0xc0001a4880})           │
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e                                                 │
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00049e420, {0x19b18c8, 0xc0003992c0})                                   │
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205                                                 │
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                                                │
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85                                                  │
 created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2                                                                         │
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
```

### Expected Behavior

K8up should work with the podSecurityContext configuration within the backup definition.

At least the operator should not crash in panic on error prone definitions. You are also running into a deadlock situation because Kubernetes won't alter/delete the Schedule without the operator running and the operator won't come up with an altered schedule spec.

However - what did work is to specify the podSecurityContext within the `ScheduleSpec` directly.

### Steps To Reproduce

```
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  labels:
    de.xarif.cdk8s: wikijs
  name: wikijs-daily-backups-c8112f87
  namespace: wikijs
spec:
  archive:
    restoreMethod:
      s3:
        accessKeyIDSecretRef:
          key: root-user
          name: k8up
        bucket: archive
        endpoint: http://minio.k8up.svc.cluster.local:9000
        secretAccessKeySecretRef:
          key: root-password
          name: k8up
    schedule: 0 0 1 * *
  backend:
    repoPasswordSecretRef:
      key: k8up-password
      name: k8up
    s3:
      accessKeyIDSecretRef:
        key: root-user
        name: k8up
      bucket: backups
      endpoint: http://minio.k8up.svc.cluster.local:9000
      secretAccessKeySecretRef:
        key: root-password
        name: k8up
  backup:
    failedJobsHistoryLimit: 2
    schedule: 0 4 * * *
    successfulJobsHistoryLimit: 1
    podSecurityContext:
      runAsUser: 0
  check:
    schedule: 0 1 * * 1
  prune:
    retention:
      keepLast: 5
      keepMonthly: 5
      keepWeekly: 3
    schedule: 0 1 * * 0

```

### Version of K8up

ghcr.io/k8up-io/k8up:v2.1.2

### Version of Kubernetes

v1.22.2+k3s2

### Distribution of Kubernetes

k3s

**Comment by Kidswiss** [comment]
Hi @ThomasSteinbach 

I was able to reproduce this. As a workaround you can set the schedules podSecurityContext to an empty object:
```yaml
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-test
spec:
  podSecurityContext: {}
```

And then set it in the backup podSecurityContext separately. There's a merge, so the backup's settings will have precedence. That merge is what actually causes this crash, as it wants to merge with a nil value.

But yeah, it should really not crash if the schedule podSecurityContext is nil. Note for whoever will fix this, here's the faulty line: https://github.com/k8up-io/k8up/blob/master/operator/handler/schedule.go#L139. We should also add a test case for this constellation.
