### ISSUE TITLE
Add Open Stack Authentication for Swift Backend

### ISSUE THREAD

**Issue by sashokbg** [k8up-io/k8up#655]
### Summary

**As** "developer"\
**I want** "to configure open stack authentication"\
**So that** "I can use open stack swift backends"

### Context

Currently the swift backend only accepts a path and a container and authentication is handled by adding global variables.

It would be interesting to provide another field like "openStackAuthSecret" which points to a kubernetes secret, containing all the required env variables defined by open stack:

Example:

- OS_AUTH_URL
- OS_IDENTITY_API_VERSION
- OS_USER_DOMAIN_NAME
- OS_PROJECT_DOMAIN_NAME
- OS_TENANT_ID
- OS_TENANT_NAME
- OS_USERNAME
- OS_PASSWORD
- OS_REGION_NAME

### Further links

- https://docs.openstack.org/zh_CN/user-guide/common/cli-set-environment-variables-using-openstack-rc.html

### Implementation Ideas

Example secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: "open-stack-secret"
stringData:
  OS_AUTH_URL: ""
  OS_IDENTITY_API_VERSION: "3"
  OS_USER_DOMAIN_NAME: "Default"
  OS_PROJECT_DOMAIN_NAME: "Default"
  OS_TENANT_ID: ""
  OS_TENANT_NAME: ""
  OS_USERNAME: ""
  OS_PASSWORD: ""
  OS_REGION_NAME: ""
```

Example backend config with backend swift
```
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-test
spec:
  tags:
    - prod
    - archive
    - important
  failedJobsHistoryLimit: 4
  successfulJobsHistoryLimit: 0
  backend:
    repoPasswordSecretRef:
      name: "backup-encryption"
      key: "password"
    swift:
      path: /archive1
      container: home-cloud-backups
      openStackAuthSecret: open-stack-secret
```
