### ISSUE TITLE
k8up.io/backupcommand-container annotation is ignored

### ISSUE THREAD

**Issue by JCL38-ORANGE** [k8up-io/k8up#827]
### Description

When I put the annotation k8up.io/backupcommand-container on my pod in order to choose the container on which the backup is initiated, the annotation is ignored. The backup is always initiated on the container 0 of the pod. 

### Additional Context

**My pod structure is :** 
```
apiVersion: v1
kind: Pod
metadata:
  annotations: 
    k8up.io/backupcommand: /usr/bin/mysqldump -uroot -ppassword --all-databases
    k8up.io/backupcommand-container: sidecar
spec:
  containers:
  - name: audit
  - name: mariadb
  - name: sidecar
```

### Logs

```shell
2023-03-20T09:01:56Z    INFO    k8up.restic.restic.stdinBackup    starting stdin backup    {"filename": "/coaby-3d6f72c4-7e93-432d-a2b2-9577a2eb4dd3-audit", "extension": ""}  
=>audit container is choosen instead of sidecar container
```

### Expected Behavior

The sidecar container must be choosen instead of the audit container.

### Version of K8up

v2.6.0

### Version of Kubernetes

v1.24.9+k3s2

### Distribution of Kubernetes

k3s
