### ISSUE TITLE
could not load snapshot xxxxxx: ciphertext verification failed

### ISSUE THREAD

**Issue by JCL38-ORANGE** [k8up-io/k8up#835]
### Description

I am facing with a ciphertext verification failed since two days on my snaphosts. For the moment, I don"t know how I meet this situation.
It was working well since about 10 days. 

### Additional Context

My schedule configuration is the following and loaded with fluxcd/kustomize : 
```
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule
spec:
  backend:
    repoPasswordSecretRef:
      name: repo-password
      key: password
    s3:
      endpoint: ${s3_endpoint}
      bucket: ${s3_bucket}
      accessKeyIDSecretRef:
        name: access-key
        key: access_key
      secretAccessKeySecretRef:
        name: secret-key
        key: secret_key
  backup:
    schedule: '0 */1 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
    promURL: ${s3_endpoint}
  check:
    schedule: '0 */1 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
  prune:
    schedule: '0 */1 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
    retention:
      keepLast: 3
      keepDaily: 1
  podSecurityContext:
    runAsUser: 0

```

### Logs

```shell
2023-04-03T07:11:28Z    INFO    k8up.restic.restic.snapshots.restic.stderr    could not load snapshot 0a7de556: ciphertext verification failed
```
```
2023-04-03T07:11:54Z    INFO    k8up.restic.restic.backup.progress    restic output    {"msg": "Error loading snapshot 0a7de556: ciphertext verification failed"}
```
```


### Expected Behavior

repository unlock command will be usefull/suitable

### Steps To Reproduce

_No response_

### Version of K8up

2.6.0

### Version of Kubernetes

v1.24.9+k3s2

### Distribution of Kubernetes

k3s
