### ISSUE TITLE
crash when getting list of snapshots

### ISSUE THREAD

**Issue by sebschlue** [k8up-io/k8up#871]
### Description

I have deployed k8up via helm chart version 4.3.0 with no custom values. I have then set up a simple hourly backup schedule for a namespace with several volumes.

Restic backup itself seems to work fine but it seems that backup pod crashes after "restic backup" step at the "restic snapshots" step.

Due to this crash at the end, the whole backup is considered to have failed. 

Due to pod crashloop, I end up with 6 new restic snapshots for each volume and each backup invocation :) 

Restic repo is healthy, I can run "rest snapshot", "restic check" and "restic check --read-data" from local restic cli with no issues.

I can also run 

```
restic snapshots --option "" --json
```
locally without crash.

### Additional Context

k8s is AWS EKS 1.24

### Logs

```shell
2023-07-03T19:04:00Z    INFO    k8up.restic.restic.backup.progress      restic output   {"msg": "Warning: at least one source file could not be read"}
2023-07-03T19:04:00Z    INFO    k8up.restic.restic.backup       backup finished, sending snapshot list
2023-07-03T19:04:00Z    INFO    k8up.restic.restic.snapshots    getting list of snapshots
2023-07-03T19:04:00Z    INFO    k8up.restic.restic.snapshots.command    restic command  {"path": "/usr/local/bin/restic", "args": ["snapshots", "--option", "", "--json"]}
2023-07-03T19:04:00Z    INFO    k8up.restic.restic.snapshots.command    Defining RESTIC_PROGRESS_FPS    {"frequency": 0.016666666666666666}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x141887e]

goroutine 1 [running]:
github.com/k8up-io/k8up/v2/restic/kubernetes.filterByRepo(...)
        /home/runner/work/k8up/k8up/restic/kubernetes/snapshots.go:123
github.com/k8up-io/k8up/v2/restic/kubernetes.SyncSnapshotList({0x1a42388, 0xc0002f6380}, {0xc000876000, 0x286, 0x0?}, {0xc000048009, 0xa}, {0xc00004c012, 0x2d})
        /home/runner/work/k8up/k8up/restic/kubernetes/snapshots.go:29 +0x35e
github.com/k8up-io/k8up/v2/restic/cli.(*Restic).sendSnapshotList(0xc000174000)
        /home/runner/work/k8up/k8up/restic/cli/backup.go:116 +0x19b
github.com/k8up-io/k8up/v2/restic/cli.(*Restic).Backup(0xc000174000, {0x17bcee5, 0x5}, {0x0, 0x0, 0x0})
        /home/runner/work/k8up/k8up/restic/cli/backup.go:46 +0x2da
github.com/k8up-io/k8up/v2/cmd/restic.doBackup({0x1a423c0?, 0xc00004e020?}, 0xc000456360?, {{0x1a44e50?, 0xc000456360?}, 0xc00014a2a0?})
        /home/runner/work/k8up/k8up/cmd/restic/main.go:234 +0x105
github.com/k8up-io/k8up/v2/cmd/restic.run({0x1a423c0, 0xc00004e020}, 0x1a44e50?, {{0x1a44e50?, 0xc000456360?}, 0x1a30ec8?})
        /home/runner/work/k8up/k8up/cmd/restic/main.go:129 +0xbf
github.com/k8up-io/k8up/v2/cmd/restic.resticMain(0xc0004af700)
        /home/runner/work/k8up/k8up/cmd/restic/main.go:113 +0x2a7
github.com/urfave/cli/v2.(*Command).Run(0x2598960, 0xc0004af700, {0xc00014db90, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/command.go:271 +0xa42
github.com/urfave/cli/v2.(*Command).Run(0xc000002f00, 0xc0004af000, {0xc00003e060, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/command.go:264 +0xc97
github.com/urfave/cli/v2.(*App).RunContext(0xc0003d8000, {0x1a423c0?, 0xc00004e020}, {0xc00003e060, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/app.go:333 +0x665
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/app.go:310
main.main()
        /home/runner/work/k8up/k8up/cmd/k8up/main.go:30 +0x45
```

### Expected Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x141887e]
```

should not occur :) 

### Steps To Reproduce

```
apiVersion: v1
kind: Secret
metadata:
  name: backup-repo
type: Opaque
stringData:
  password: XXX
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  username: XXX
  password: XXX
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule
spec:
  backend:
    s3:
      endpoint: http://minio.svc-minio:9000/
      bucket: k8s-pv-backups
      accessKeyIDSecretRef:
        name: s3-credentials
        key: username
      secretAccessKeySecretRef:
        name: s3-credentials
        key: password
    repoPasswordSecretRef:
      name: backup-repo
      key: password
  backup:
    schedule: '0 * * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '0 1 * * 1'
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14
```

### Version of K8up

4.3.0

### Version of Kubernetes

1.24

### Distribution of Kubernetes

AWS EKS
