### ISSUE TITLE
Custom Annotations for Backup-Jobs

### ISSUE THREAD

**Issue by sebschlue** [k8up-io/k8up#885]
### Summary

As a user of k8up backup operator, I would like to be able to specify custom annotations for backup jobs.

This would be useful to implement "solution #1" as desribed in https://itnext.io/three-ways-to-use-linkerd-with-kubernetes-jobs-c12ccc6d4c7c

It would then be possible to have a job template like this:

```
jobTemplate:
  spec:
    template:
      metadata:
        annotations:
          linkerd.io/inject: disabled
````

### Context

Please see https://itnext.io/three-ways-to-use-linkerd-with-kubernetes-jobs-c12ccc6d4c7c why this is important for users that also use linkerd and have auto-injection enabled at a namespace level.

**Comment by arska** [comment]
This is possible via PodConfig — annotations set on the PodConfig resource are merged into the Job's pod template (see `operator/job/job.go`).

Example:
```yaml
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: my-podconfig
  annotations:
    linkerd.io/inject: disabled
spec:
  template:
    spec:
      containers:
        - name: backup
```

Then reference it in your Backup or Schedule with `podConfigRef`. Closing as the feature exists via PodConfig.
