### ISSUE TITLE
Support container Security Context

### ISSUE THREAD

**Issue by mhutter** [k8up-io/k8up#902]
### Summary

**As** a security-conscious operator\
**I want** to configure container security contexts\
**So that** I can make K8up pods compliant to the "restricted" security standard\
**So that** I can enforce a high security standard on my cluster.

### Context

K8up already supports configuring the `PodSecurityContext` on the Pod level via a field in BackupSpec. However, there is also `SecurityContext`, which is a similar construct on the Contaner level: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container

In order to be compliant with the "restricted" [Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards), both fields must be edited.

Bonus: Make the defaults compatible with "restricted" :-)

### Further links

- https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
- https://kubernetes.io/docs/concepts/security/pod-security-standards/

### Implementation Ideas

Expose field in `Backup` spec

**Comment by megian** [comment]
#584 as a reference

**Comment by arska** [comment]
Container-level security context can be configured via PodConfig, which merges the full pod spec including container specs:

```yaml
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: restricted-security
spec:
  template:
    spec:
      containers:
        - name: k8up
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
```

This covers the "restricted" Pod Security Standard requirements at the container level. The pod-level `podSecurityContext` field on BackupSpec/ScheduleSpec handles the pod-level settings.

Closing as this is already possible via PodConfig. Feel free to reopen if the PodConfig approach doesn't cover your specific use case.
